// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcrulfdobtmfxzpuyryn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjcnVsZmRvYnRtZnh6cHV5cnluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwNjEyMzMsImV4cCI6MjA4MTYzNzIzM30.VRo0gOOtaukvUpJn_gxsl81xIQ6uNh9pRvf-8LGNcjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});